import File from './../../Icons/file.svg';
import Audio from './../../Icons/audio.svg';
import Code from './../../Icons/code.svg';
import Css from './../../Icons/css.svg';
import Docx from './../../Icons/docx.svg';
import Exe from './../../Icons/exe.svg';
import Folder from './../../Icons/folder.svg';
import Font from './../../Icons/font.svg';
import Html from './../../Icons/html.svg';
import Image from './../../Icons/image.svg';
import Js from './../../Icons/js.svg';
import Key from './../../Icons/key.svg';
import Pdf from './../../Icons/pdf.svg';
import Pptx from './../../Icons/pptx.svg';
import Psd from './../../Icons/psd.svg';
import Rar from './../../Icons/rar.svg';
import Sevez from './../../Icons/sevez.svg';
import Txt from './../../Icons/txt.svg';
import Video from './../../Icons/video.svg';
import Xls from './../../Icons/xls.svg';
import Zip from './../../Icons/zip.svg';

export const file = File;
export const audio = Audio;
export const code = Code;
export const css = Css;
export const docx = Docx;
export const exe = Exe;
export const folder = Folder;
export const font = Font;
export const html = Html;
export const image = Image;
export const js = Js;
export const key = Key;
export const pdf = Pdf;
export const pptx = Pptx;
export const psd = Psd;
export const rar = Rar;
export const sevez = Sevez;
export const txt = Txt;
export const video = Video;
export const xls = Xls;
export const zip = Zip;